/****** Object:  Table [dbo].[EVENTOS]    Script Date: 28/05/2023 20:19:24 ******/
DROP TABLE [dbo].[BANDEIRAS_COMERCIAIS]
GO

/****** Object:  Table [dbo].[EVENTOS]    Script Date: 28/05/2023 20:19:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BANDEIRAS_COMERCIAIS](
	[ID] [int] NOT NULL,
	[DATA_INCLUSAO] [Datetime2] NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [Datetime2] NULL,
	[DESCRICAO] [varchar](75) NOT NULL
 CONSTRAINT [PK_BANDEIRAS_COMERCIAIS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[BANDEIRAS_COMERCIAIS] ADD CONSTRAINT DF_BANDEIRAS_COMERCIAIS_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO