ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [DF_PESSOAS_JURIDICAS_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 16/01/2024 15:05:42 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PESSOAS_JURIDICAS]') AND type in (N'U'))
DROP TABLE [dbo].[PESSOAS_JURIDICAS]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 16/01/2024 15:05:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOAS_JURIDICAS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDPESSOA] [uniqueidentifier] NOT NULL,
	[CNPJ] [char](14) NOT NULL,
	[DATA_FUNDACAO] [date] NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NULL,
	[LOGOTIPO] [varbinary](max) NULL,
	[RAZAO_SOCIAL] [varchar](100) NOT NULL,
 CONSTRAINT [PK_PESSOAS_JURIDICAS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] ADD  CONSTRAINT [DF_PESSOAS_JURIDICAS_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS] FOREIGN KEY([GUIDPESSOA])
REFERENCES [dbo].[PESSOAS] ([GUID])
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] CHECK CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

DROP INDEX [IX_CNPJ] ON [dbo].[PESSOAS_JURIDICAS]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_CNPJ]    Script Date: 16/01/2024 15:06:00 ******/
CREATE NONCLUSTERED INDEX [IX_CNPJ] ON [dbo].[PESSOAS_JURIDICAS]
(
	[CNPJ] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

DROP INDEX [UQ_CNPJ] ON [dbo].[PESSOAS_JURIDICAS]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [UQ_CNPJ]    Script Date: 16/01/2024 15:06:17 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UQ_CNPJ] ON [dbo].[PESSOAS_JURIDICAS]
(
	[CNPJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
