ALTER TABLE [dbo].[USUARIOS] DROP CONSTRAINT [FK_USUARIOS_PESSOAS_FISICAS]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 19/05/2023 17:15:10 ******/
DROP TABLE [dbo].[USUARIOS]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 19/05/2023 17:15:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS](
	[GUID] [uniqueIdentifier] NOT NULL,
	[GUIDCOLABORADOR] [uniqueIdentifier] NULL,
	[DATA_INCLUSAO] [Datetime2] NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [Datetime2] NULL,
	[EMAIL] [varchar] (75) NULL,
	[USERNAME] [varchar](75) NOT NULL,
	[PASSWORD] [varchar](32) NOT NULL,
	[IDASPNETUSER] [nvarchar] (450) NULL,
	[DATA_PRIMEIRO_ACESSO] [DATETIME2] NULL,
 CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS_PESSOAS_FISICAS] FOREIGN KEY([GUIDCOLABORADOR])
REFERENCES [dbo].[PESSOAS_FISICAS] ([GUID])
GO

ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_PESSOAS_FISICAS]
GO

ALTER TABLE [dbo].[USUARIOS] ADD CONSTRAINT DF_USUARIOS_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO