ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [DF_PESSOAS_JURIDICAS_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 18/03/2024 16:01:52 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PESSOAS_JURIDICAS]') AND type in (N'U'))
DROP TABLE [dbo].[PESSOAS_JURIDICAS]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 18/03/2024 16:01:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOAS_JURIDICAS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDPESSOA] [uniqueidentifier] NOT NULL,
	[CNPJ] [char](14) NOT NULL,
	[DATA_FUNDACAO] [date] NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NULL,
	[LOGOTIPO] [varbinary](max) NULL,
	[RAZAO_SOCIAL] [varchar](100) NOT NULL,
	[IDUNIDADE_NEGOCIO] [int] NOT NULL,
 CONSTRAINT [PK_PESSOAS_JURIDICAS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] ADD  CONSTRAINT [DF_PESSOAS_JURIDICAS_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO] FOREIGN KEY([IDUNIDADE_NEGOCIO])
REFERENCES [dbo].[UNIDADES_NEGOCIO] ([ID])
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] CHECK CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS] FOREIGN KEY([GUIDPESSOA])
REFERENCES [dbo].[PESSOAS] ([GUID])
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] CHECK CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

