USE [UniPayCheck]
GO

/****** Object:  Table [dbo].[TOTALIZADORES]    Script Date: 18/06/2023 14:51:36 ******/
DROP TABLE [dbo].[TOTALIZADORES]
GO

/****** Object:  Table [dbo].[TOTALIZADORES]    Script Date: 18/06/2023 14:51:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TOTALIZADORES](
	[ID] [int] NOT NULL,
	[DATA_INCLUSAO] [Datetime2] NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [Datetime2] NULL,
	[DESCRICAO] [varchar](75) NOT NULL,
	[OBSERVACOES] [varchar](max) NULL,
 CONSTRAINT [PK_TOTALIZADORES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TOTALIZADORES] ADD CONSTRAINT DF_TOTALIZADORES_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO