USE [UniPayCheck]
GO

/****** Object:  Table [dbo].[TOTALIZADORES]    Script Date: 28/05/2023 20:20:06 ******/
DROP TABLE [dbo].[TOTALIZADORES]
GO

/****** Object:  Table [dbo].[TOTALIZADORES]    Script Date: 28/05/2023 20:20:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TOTALIZADORES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRICAO] [varchar](75) NOT NULL,
	[OBSERVACOES] [varchar](max) NULL,
 CONSTRAINT [PK_TOTALIZADORES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO