USE [UniPayCheck]
GO

EXEC sys.sp_dropextendedproperty @name=N'MS_Description' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MATRICULAS', @level2type=N'COLUMN',@level2name=N'FORMA_PAGAMENTO'
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [FK_MATRICULAS_PESSOAS_JURIDICAS]
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [FK_MATRICULAS_PESSOAS_FISICAS]
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [DF_MATRICULAS_SALARIO_NOMINAL]
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [DF_MATRICULAS_CARGA_HORARIA]
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [DF_MATRICULAS_FORMA_PAGAMENTO]
GO

ALTER TABLE [dbo].[MATRICULAS] DROP CONSTRAINT [DF_MATRICULAS_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[MATRICULAS]    Script Date: 15/12/2023 12:26:05 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MATRICULAS]') AND type in (N'U'))
DROP TABLE [dbo].[MATRICULAS]
GO

/****** Object:  Table [dbo].[MATRICULAS]    Script Date: 15/12/2023 12:26:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS](
	[GUID] [uniqueidentifier] NOT NULL,
	[MATRICULA] [varchar](20) NOT NULL,
	[DATA_ADMISSAO] [date] NOT NULL,
	[DATA_DEMISSAO] [date] NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NULL,
	[DESCRICAO_CARGO] [varchar](75) NOT NULL,
	[DESCRICAO_SETOR] [varchar](75) NOT NULL,
	[FAIXA_IR] [smallint] NOT NULL,
	[FAIXA_SF] [smallint] NOT NULL,
	[GUIDCOLABORADOR] [uniqueidentifier] NOT NULL,
	[GUIDEMPREGADOR] [uniqueidentifier] NOT NULL,
	[AGENCIA] [varchar](9) NULL,
	[BANCO] [varchar](3) NULL,
	[FORMA_PAGAMENTO] [char](1) NOT NULL,
	[CARGA_HORARIA] [decimal](6, 2) NOT NULL,
	[CONTA] [varchar](15) NULL,
	[SALARIO_NOMINAL] [varchar](128) NOT NULL,
 CONSTRAINT [PK_MATRICULAS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  CONSTRAINT [DF_MATRICULAS_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  DEFAULT (0) FOR [FAIXA_IR]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  DEFAULT (0) FOR [FAIXA_SF]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  CONSTRAINT [DF_MATRICULAS_FORMA_PAGAMENTO]  DEFAULT ('O') FOR [FORMA_PAGAMENTO]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  CONSTRAINT [DF_MATRICULAS_CARGA_HORARIA]  DEFAULT ('220') FOR [CARGA_HORARIA]
GO

ALTER TABLE [dbo].[MATRICULAS] ADD  CONSTRAINT [DF_MATRICULAS_SALARIO_NOMINAL]  DEFAULT ('0.01') FOR [SALARIO_NOMINAL]
GO

ALTER TABLE [dbo].[MATRICULAS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_PESSOAS_FISICAS] FOREIGN KEY([GUIDCOLABORADOR])
REFERENCES [dbo].[PESSOAS_FISICAS] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS] CHECK CONSTRAINT [FK_MATRICULAS_PESSOAS_FISICAS]
GO

ALTER TABLE [dbo].[MATRICULAS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_PESSOAS_JURIDICAS] FOREIGN KEY([GUIDEMPREGADOR])
REFERENCES [dbo].[PESSOAS_JURIDICAS] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS] CHECK CONSTRAINT [FK_MATRICULAS_PESSOAS_JURIDICAS]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'(R)elação Bancária; (O)utros.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'MATRICULAS', @level2type=N'COLUMN',@level2name=N'FORMA_PAGAMENTO'
GO