USE [UniPayCheck]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] DROP CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MATRICULAS]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]    Script Date: 28/05/2023 19:29:40 ******/
DROP TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]    Script Date: 28/05/2023 19:29:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDMATRICULA] [uniqueidentifier] NOT NULL,
	[COMPETENCIA] [char](8) NOT NULL,
	[DATA_INCLUSAO] [Datetime2] NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [Datetime2] NULL,
 CONSTRAINT [PK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MATRICULAS] FOREIGN KEY([GUIDMATRICULA])
REFERENCES [dbo].[MATRICULAS] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] CHECK CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MATRICULAS]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] ADD CONSTRAINT DF_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO