USE [UniPayCheck]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] DROP CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] DROP CONSTRAINT [DF_MATRICULAS_ESPELHOS_PONTO_DATA_INCLUSAO]
GO

DROP TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO]
GO

/****** Object:  Table [dbo].[MATRICULAS_ESPELHOS_PONTO]    Script Date: 22/08/2023 14:09:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO](
	[GUID] [uniqueidentifier] NOT NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NULL,
	[COMPETENCIA] [char](6) NULL,
	[GUIDMATRICULA] [uniqueidentifier] NOT NULL,
	[DATA_CONFIRMACAO] [datetime2](7) NULL,
	[IP_CONFIRMACAO] [varbinary](16) NULL,
 CONSTRAINT [PK_MATRICULAS_ESPELHO_PONTO] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] ADD  CONSTRAINT [DF_MATRICULAS_ESPELHOS_PONTO_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS] FOREIGN KEY([GUIDMATRICULA])
REFERENCES [dbo].[MATRICULAS] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] CHECK CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS]
GO