/****** Object:  Table [dbo].[USUARIOS]    Script Date: 19/05/2023 17:15:10 ******/
DROP TABLE [dbo].[USUARIOS_NOTIFICACOES]
GO

/****** Object:  Table [dbo].[USUARIOS]    Script Date: 19/05/2023 17:15:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[USUARIOS_NOTIFICACOES](
	[GUID] [uniqueIdentifier] NOT NULL,
	[GUIDUSUARIO] [uniqueIdentifier] NULL,
	[DATA_INCLUSAO] DATETIME2 NOT NULL,
	[DATA_LEITURA] DATETIME2 NULL,
 CONSTRAINT [PK_USUARIOS_NOTIFICACOES] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[USUARIOS_NOTIFICACOES] ADD CONSTRAINT DF_USUARIOS_NOTIFICACOES_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO