USE [UniPayCheck]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] DROP CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_MATRICULAS_ESPELHOS_PONTO]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] DROP CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_CALCULOS]
GO

/****** Object:  Table [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS]    Script Date: 22/08/2023 09:40:14 ******/
DROP TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS]
GO

/****** Object:  Table [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS]    Script Date: 22/08/2023 09:40:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDMATRICULA_ESPELHO_PONTO] [uniqueidentifier] NOT NULL,
	[IDCALCULO] [int] NOT NULL,
	[REFERENCIA] [decimal](25, 10) NULL,
	[VALOR] [decimal](25, 10) NOT NULL,
 CONSTRAINT [PK_MATRICULAS_ESPELHOS_PONTO_CALCULOS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_CALCULOS] FOREIGN KEY([IDCALCULO])
REFERENCES [dbo].[CALCULOS] ([ID])
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] CHECK CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_CALCULOS]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_MATRICULAS_ESPELHOS_PONTO] FOREIGN KEY([GUIDMATRICULA_ESPELHO_PONTO])
REFERENCES [dbo].[MATRICULAS_ESPELHOS_PONTO] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] CHECK CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_CALCULOS_MATRICULAS_ESPELHOS_PONTO]
GO

