USE [UniPayCheck]
GO

/****** Object:  Table [dbo].[CALCULOS]    Script Date: 18/06/2023 14:50:00 ******/
DROP TABLE [dbo].[CALCULOS]
GO

/****** Object:  Table [dbo].[CALCULOS]    Script Date: 18/06/2023 14:50:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CALCULOS](
	[ID] [int] NOT NULL,
	[DESCRICAO] [varchar](75) NOT NULL,
	[OBSERVACOES] [varchar](max) NULL,
 CONSTRAINT [PK_CALCULOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO