ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] DROP CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] DROP CONSTRAINT [DF_MATRICULAS_ESPELHOS_PONTO_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[MATRICULAS_ESPELHOS_PONTO]    Script Date: 16/01/2024 14:24:20 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MATRICULAS_ESPELHOS_PONTO]') AND type in (N'U'))
DROP TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO]
GO

/****** Object:  Table [dbo].[MATRICULAS_ESPELHOS_PONTO]    Script Date: 16/01/2024 14:24:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO](
	[GUID] [uniqueidentifier] NOT NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NULL,
	[COMPETENCIA] [char](6) NULL,
	[GUIDMATRICULA] [uniqueidentifier] NOT NULL,
	[DATA_CONFIRMACAO] [datetime2](7) NULL,
	[IP_CONFIRMACAO] [varbinary](16) NULL,
	[CONTEUDO_ARQUIVO] [varchar](max) NULL,
 CONSTRAINT [PK_MATRICULAS_ESPELHO_PONTO] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] ADD  CONSTRAINT [DF_MATRICULAS_ESPELHOS_PONTO_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS] FOREIGN KEY([GUIDMATRICULA])
REFERENCES [dbo].[MATRICULAS] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_ESPELHOS_PONTO] CHECK CONSTRAINT [FK_MATRICULAS_ESPELHOS_PONTO_MATRICULAS]
GO

--DROP INDEX [IX_MATRICULAS_ESPELHOS_PONTO_COMPETENCIA] ON [dbo].[MATRICULAS_ESPELHOS_PONTO]
--GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_MATRICULAS_ESPELHOS_PONTO_COMPETENCIA]    Script Date: 16/01/2024 14:43:07 ******/
CREATE NONCLUSTERED INDEX [IX_MATRICULAS_ESPELHOS_PONTO_COMPETENCIA] ON [dbo].[MATRICULAS_ESPELHOS_PONTO]
(
	[COMPETENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO