ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] DROP CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] DROP CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_EVENTOS]
GO

/****** Object: Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS]    Script Date: 28/05/2023 19:32:01 ******/
DROP TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS]    Script Date: 28/05/2023 19:32:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO] [uniqueidentifier] NOT NULL,
	[IDEVENTO] [int] NOT NULL,
	[REFERENCIA] [decimal](25, 10) NULL,
	[VALOR] [VARCHAR](128) NOT NULL,
 CONSTRAINT [PK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_EVENTOS] FOREIGN KEY([IDEVENTO])
REFERENCES [dbo].[EVENTOS] ([ID])
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] CHECK CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_EVENTOS]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] FOREIGN KEY([GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO])
REFERENCES [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] CHECK CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO

