/****** Object:  Table [dbo].[EVENTOS]    Script Date: 28/05/2023 20:19:24 ******/
DROP TABLE [dbo].[PUBLICACOES]
GO

/****** Object:  Table [dbo].[EVENTOS]    Script Date: 28/05/2023 20:19:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[PUBLICACOES](
	[ID] [int] NOT NULL,
	[DATA_INCLUSAO] DATETIMEOFFSET NOT NULL,
	[DATA_ULTIMA_ALTERACAO] DATETIMEOFFSET NULL,
	[TITULO] [varchar](150) NOT NULL,
	[RESUMO] [VARCHAR](MAX) NULL,
	[TEXTO] [VARCHAR](MAX) NULL,
	[CONTEUDO_IMAGEM] [VARBINARY](MAX) NULL,
	[EXTENSAO_IMAGEM] [VARCHAR](6) NULL,
	[CONTEUDO_ARQUIVO] [VARBINARY](MAX) NULL,
	[EXTENSAO_ARQUIVO] [VARCHAR](6) NULL,
	[DATA_APRESENTACAO] DATETIMEOFFSET NOT NULL,
	[DATA_VALIDADE] DATETIMEOFFSET NULL,

 CONSTRAINT [PK_PUBLICACOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[PUBLICACOES] ADD CONSTRAINT DF_PUBLICACOES_DATA_INCLUSAO DEFAULT GETUTCDATE() FOR [DATA_INCLUSAO]
GO