USE [unipaycheck]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS] DROP CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS]    Script Date: 27/08/2025 15:50:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS]') AND type in (N'U'))
DROP TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS]    Script Date: 27/08/2025 15:50:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO] [uniqueidentifier] NOT NULL,
	[TEXTO] [varchar](200) NOT NULL,
 CONSTRAINT [PK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] FOREIGN KEY([GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO])
REFERENCES [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS] CHECK CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_MENSAGENS_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO

