ALTER TABLE [dbo].[PUBLICACOES] DROP CONSTRAINT [DF_PUBLICACOES_OCULTAR_PUBLICACAO]
GO

ALTER TABLE [dbo].[PUBLICACOES] DROP CONSTRAINT [DF_PUBLICACOES_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[PUBLICACOES]    Script Date: 28/02/2024 02:38:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PUBLICACOES]') AND type in (N'U'))
DROP TABLE [dbo].[PUBLICACOES]
GO

/****** Object:  Table [dbo].[PUBLICACOES]    Script Date: 28/02/2024 02:38:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PUBLICACOES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DATA_INCLUSAO] [datetimeoffset](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetimeoffset](7) NULL,
	[TITULO] [varchar](150) NOT NULL,
	[RESUMO] [varchar](max) NULL,
	[TEXTO] [varchar](max) NULL,
	[CONTEUDO_IMAGEM] [varbinary](max) NULL,
	[EXTENSAO_IMAGEM] [varchar](6) NULL,
	[NOME_IMAGEM] [varchar](250) NULL,
	[CONTEUDO_ARQUIVO] [varbinary](max) NULL,
	[EXTENSAO_ARQUIVO] [varchar](6) NULL,
	[NOME_ARQUIVO] [varchar](250) NULL,
	[DATA_APRESENTACAO] [date] NOT NULL,
	[DATA_VALIDADE] [date] NULL,
	[OCULTAR_PUBLICACAO] [bit] NOT NULL,
 CONSTRAINT [PK_PUBLICACOES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PUBLICACOES] ADD  CONSTRAINT [DF_PUBLICACOES_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO

ALTER TABLE [dbo].[PUBLICACOES] ADD  CONSTRAINT [DF_PUBLICACOES_OCULTAR_PUBLICACAO]  DEFAULT ((0)) FOR [OCULTAR_PUBLICACAO]
GO