USE [unipaycheck]
GO

--ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] DROP CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
--GO

--ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] DROP CONSTRAINT [DF__MATRICULA__DATA___10F65906]
--GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES]    Script Date: 27/08/2025 15:54:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES]') AND type in (N'U'))
DROP TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES]
GO

/****** Object:  Table [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES]    Script Date: 27/08/2025 15:54:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO] [uniqueidentifier] NOT NULL,
	[CONTEUDO] [varchar](MAX) NOT NULL,
	[DATA_ENVIO] [datetime2](7) NOT NULL,
	[DATA_LEITURA] [datetime2](7) NULL,
	[IP_LEITURA] [varbinary](16) NULL,
 CONSTRAINT [PK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] ADD  DEFAULT (getdate()) FOR [DATA_ENVIO]
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES]  WITH CHECK ADD  CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] FOREIGN KEY([GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO])
REFERENCES [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] ([GUID])
GO

ALTER TABLE [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] CHECK CONSTRAINT [FK_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES_MATRICULAS_DEMONSTRATIVOS_PAGAMENTO]
GO