DROP VIEW [dbo].[vwUsuariosNotificacoes]
GO

/****** Object:  View [dbo].[vwRecursos_CTE]    Script Date: 29/12/2021 23:50:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[vwUsuariosNotificacoes]
AS

     SELECT DISTINCT 'DP' AS TIPO,
                     N.[GUID],
				     U.[GUID] AS 'GUIDUSUARIO',
                     N.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO],
				     N.[CONTEUDO],
                     N.[DATA_ENVIO],
				     N.[DATA_LEITURA],
				     N.[IP_LEITURA]
       FROM [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_NOTIFICACOES] N WITH (NOLOCK)
 INNER JOIN [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] P WITH (NOLOCK)
         ON N.GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO = P.[GUID]
 INNER JOIN [dbo].[MATRICULAS] M WITH (NOLOCK)
         ON P.GUIDMATRICULA = M.[GUID]
 INNER JOIN [dbo].[USUARIOS] U WITH (NOLOCK)
         ON M.[GUIDCOLABORADOR] = U.[GUIDCOLABORADOR]

GO