--EXEC [dbo].[spDemonstrativoPagamento] '20200601','FC7372FD-EBCC-4AF5-B5A8-8D17FABB6336', 'A'

USE [UniPayCheck]
GO

/****** Object:  StoredProcedure [dbo].[spDemonstrativoPagamento]    Script Date: 15/06/2023 00:58:15 ******/
DROP PROCEDURE [dbo].[spDemonstrativoPagamento]
GO

/****** Object:  StoredProcedure [dbo].[spDemonstrativoPagamento]    Script Date: 15/06/2023 00:58:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spDemonstrativoPagamento]
	@Competencia Char(8),
	@GuidMatricula UniqueIdentifier,
	@Modelo Char(1) = 'S'	--A: Analítico; S: Sintético.

WITH ENCRYPTION

AS
BEGIN

IF @Modelo = 'A'
BEGIN
			  SELECT M.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula

			  SELECT PF.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
		  INNER JOIN [PESSOAS_FISICAS] PF
				  ON M.[GUIDCOLABORADOR] = PF.[GUID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula

			  SELECT PJ.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
		  INNER JOIN [PESSOAS_JURIDICAS] PJ
				  ON M.[GUIDEMPREGADOR] = PJ.[GUID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula

			  SELECT E.*,
				     MDPE.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
	 LEFT OUTER JOIN MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS MDPE
				  ON MDP.[GUID] = MDPE.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
		  INNER JOIN [EVENTOS] E
				  ON MDPE.[IDEVENTO] = E.[ID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula
			ORDER BY E.ID

			  SELECT T.*,
				     MDPT.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
	 LEFT OUTER JOIN MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_TOTALIZADORES MDPT
				  ON MDP.[GUID] = MDPT.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
		  INNER JOIN [TOTALIZADORES] T
				  ON MDPT.[IDTOTALIZADOR] = T.[ID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula
			ORDER BY T.ID

END
ELSE
BEGIN
			  SELECT MDP.*,
					 M.*,
					 PF.*,
					 PJ.*,
					 MDPE.*,
					 E.*,
					 MDPT.*,
					 T.*
				FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP
		  INNER JOIN [MATRICULAS] M
				  ON MDP.[GUIDMATRICULA] = M.[GUID]
		  INNER JOIN [PESSOAS_FISICAS] PF
				  ON M.[GUIDCOLABORADOR] = PF.[GUID]
		  INNER JOIN [PESSOAS_JURIDICAS] PJ
				  ON M.[GUIDEMPREGADOR] = PJ.[GUID]
	 LEFT OUTER JOIN MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS MDPE
				  ON MDP.[GUID] = MDPE.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
		  INNER JOIN [EVENTOS] E
				  ON MDPE.[IDEVENTO] = E.[ID]
	 LEFT OUTER JOIN MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_TOTALIZADORES MDPT
				  ON MDP.[GUID] = MDPT.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
		  INNER JOIN [TOTALIZADORES] T
				  ON MDPT.[IDTOTALIZADOR] = T.[ID]
			   WHERE MDP.[COMPETENCIA] = @Competencia
				 AND MDP.[GUIDMATRICULA] = @GuidMatricula
			ORDER BY E.ID,
					 T.ID
END

END

GO