--EXEC [UspObterMatriculasEspelhosPonto]

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterMatriculaEspelhoPontoPorCompetenciaEMatricula]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterMatriculaEspelhoPontoPorCompetenciaEMatricula]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterMatriculaEspelhoPontoPorCompetenciaEMatricula]
	@Competencia AS CHAR(8),
	@Matricula AS VARCHAR(20)

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

          SELECT MEP.[GUID], MEP.[GUIDMATRICULA], MEP.[COMPETENCIA], MEP.[DATA_INCLUSAO], MEP.[DATA_ULTIMA_ALTERACAO],
                 MEP.[DATA_CONFIRMACAO],MEP.[IP_CONFIRMACAO],MEP.[CONTEUDO_ARQUIVO],
                 M.[GUID], M.[MATRICULA], M.[DATA_ADMISSAO], M.[DATA_DEMISSAO], M.[DATA_INCLUSAO], M.[DATA_ULTIMA_ALTERACAO],
		         M.[DESCRICAO_CARGO], M.[DESCRICAO_SETOR], M.[FAIXA_IR], M.[FAIXA_SF], M.[GUIDCOLABORADOR], M.[GUIDEMPREGADOR],
		         M.[FORMA_PAGAMENTO], M.[BANCO], M.[AGENCIA], M.[CONTA], M.[DV_CONTA], M.[CARGA_HORARIA], M.[SALARIO_NOMINAL],
                 PF.[GUIDPESSOA], PF.[CPF], PF.[RG], PF.[DATA_NASCIMENTO], PF.[NOME], PF.[NUMERO_CTPS], PF.[SERIE_CTPS], PF.[UF_CTPS],
                 PJ.[GUIDPESSOA], PJ.[CNPJ], PJ.[DATA_FUNDACAO], PJ.[RAZAO_SOCIAL], PJ.[IDUNIDADE_NEGOCIO],
		         MEPC.[GUID], MEPC.[GUIDMATRICULA_ESPELHO_PONTO], MEPC.[IDCALCULO], MEPC.[VALOR],
		         C.[ID], C.[DATA_INCLUSAO], C.[DATA_ULTIMA_ALTERACAO], C.[DESCRICAO],
		         MEPM.[GUID], MEPM.[GUIDMATRICULA_ESPELHO_PONTO], MEPM.[DATA], MEPM.[MARCACAO], MEPM.[HORAS_EXTRAS_050], MEPM.[HORAS_EXTRAS_070],
				 MEPM.[HORAS_EXTRAS_100], MEPM.[HORAS_CREDITO_BH], MEPM.[HORAS_DEBITO_BH], MEPM.[HORAS_FALTAS], MEPM.[HORAS_TRABALHADAS]
            FROM [dbo].[MATRICULAS_ESPELHOS_PONTO] AS MEP WITH(NOLOCK)
      INNER JOIN [dbo].[MATRICULAS] as M WITH(NOLOCK)
              ON MEP.[GUIDMATRICULA] = M.[GUID] 
      INNER JOIN [dbo].[PESSOAS_FISICAS] AS PF WITH(NOLOCK)
              ON M.[GUIDCOLABORADOR] = PF.[GUID]
      INNER JOIN [dbo].[PESSOAS_JURIDICAS] AS PJ WITH(NOLOCK)
              ON M.[GUIDEMPREGADOR] = PJ.[GUID]
 LEFT OUTER JOIN [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] AS MEPC WITH(NOLOCK)
              ON MEP.[GUID] = MEPC.[GUIDMATRICULA_ESPELHO_PONTO]
 LEFT OUTER JOIN [dbo].[CALCULOS] AS C WITH(NOLOCK)
              ON MEPC.[IDCALCULO] = C.[ID]
 LEFT OUTER JOIN [dbo].[MATRICULAS_ESPELHOS_PONTO_MARCACOES] AS MEPM WITH(NOLOCK)
              ON MEP.[GUID] = MEPM.[GUIDMATRICULA_ESPELHO_PONTO]
		   WHERE MEP.[COMPETENCIA] = @Competencia
		     AND M.[MATRICULA] = @Matricula

GO