--EXEC [UspObterMatriculaPorMatricula] '68866'

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterMatriculaPorMatricula]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterMatriculaPorMatricula]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

 CREATE PROCEDURE [dbo].[UspObterMatriculaPorMatricula]
    @Matricula VARCHAR(20)

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

--    SELECT PJ.[GUID], PJ.[GUIDPESSOA], PJ.[CNPJ], PJ.[DATA_FUNDACAO], PJ.[LOGOTIPO], PJ.[RAZAO_SOCIAL], PJ.[IDUNIDADE_NEGOCIO],
--           P.[GUID], P.[CEP], P.[COMPLEMENTO], P.[DATA_INCLUSAO], P.[DATA_ULTIMA_ALTERACAO], P.[EMAIL], P.[NUMERO], P.[TELEFONE], P.[CHAVE_EXPORTACAO_IMPORTACAO],
--	       UN.[ID], UN.[DATA_INCLUSAO], UN.[DATA_ULTIMA_ALTERACAO], UN.[DESCRICAO]
--      FROM [dbo].[PESSOAS_JURIDICAS] AS PJ WITH(NOLOCK)
--INNER JOIN [dbo].[PESSOAS] as P WITH(NOLOCK)
--        ON [PJ].[GUIDPESSOA] = [P].[GUID]
--INNER JOIN [dbo].[UNIDADES_NEGOCIO] as UN WITH(NOLOCK)
--        ON [PJ].[IDUNIDADE_NEGOCIO] = [UN].[ID]
--	 WHERE [PJ].[CNPJ] = @Cnpj

    SELECT M.[GUID], M.[MATRICULA], M.[DATA_ADMISSAO], M.[DATA_DEMISSAO], M.[DATA_INCLUSAO], M.[DATA_ULTIMA_ALTERACAO], M.[DESCRICAO_CARGO], M.[DESCRICAO_SETOR], M.[FAIXA_IR], M.[FAIXA_SF], M.[GUIDCOLABORADOR], M.[GUIDEMPREGADOR], M.[FORMA_PAGAMENTO], M.[BANCO], M.[AGENCIA], M.[CONTA], M.[DV_CONTA], M.[CARGA_HORARIA], M.[SALARIO_NOMINAL],
	       PF.[GUID], PF.[GUIDPESSOA], PF.[CPF], PF.[FOTO], PF.[RG], PF.[DATA_NASCIMENTO], PF.[NOME], PF.[NUMERO_CTPS], PF.[SERIE_CTPS], PF.[UF_CTPS],
		   PJ.[GUID], PJ.[GUIDPESSOA], PJ.[CNPJ], PJ.[DATA_FUNDACAO], PJ.[LOGOTIPO], PJ.[RAZAO_SOCIAL], PJ.[IDUNIDADE_NEGOCIO]
      FROM [dbo].[MATRICULAS] as M WITH(NOLOCK)
INNER JOIN [dbo].[PESSOAS_FISICAS] as PF WITH(NOLOCK)
        ON [M].[GUIDCOLABORADOR] = [PF].[GUID]
INNER JOIN [dbo].[PESSOAS_JURIDICAS] as PJ WITH(NOLOCK)
        ON [M].[GUIDEMPREGADOR] = [PJ].[GUID]
	 WHERE [M].[MATRICULA] = @Matricula

GO