--EXEC [UspObterEventos]

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterPessoaFisicaPorNome]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterPessoaFisicaPorNome]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterPessoaFisicaPorNome]
	@Nome AS VARCHAR(100)

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

     SELECT PF.[GUIDPESSOA], PF.[CPF], PF.[RG], PF.[DATA_NASCIMENTO], PF.[NOME], PF.[NUMERO_CTPS], PF.[SERIE_CTPS], PF.[UF_CTPS],
            P.[GUID], P.[CEP], P.[COMPLEMENTO], P.[DATA_INCLUSAO], P.[DATA_ULTIMA_ALTERACAO], P.[EMAIL], P.[NUMERO], P.[TELEFONE]
       FROM [dbo].[PESSOAS_FISICAS] AS PF WITH(NOLOCK)
 INNER JOIN [dbo].[PESSOAS] AS P WITH(NOLOCK)
         ON PF.[GUIDPESSOA] = P.[GUID]
      WHERE PF.[NOME] = @Nome

GO