--EXEC [UspObterCalculoPorId] 1

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterCalculoPorId]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterCalculoPorId]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterCalculoPorId]
	@Id INT

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

 SELECT C.[ID],
        C.[DATA_INCLUSAO],
        C.[DATA_ULTIMA_ALTERACAO],
        C.[DESCRICAO],
	    C.[OBSERVACOES]
   FROM [dbo].[CALCULOS] AS C WITH(NOLOCK)
  WHERE [C].[ID] = @Id 

GO