--EXEC [dbo].[UspObterGraficoComposicaoSalarial] '3D12DFFE-FD7B-4477-92CC-4249248D8F6C'

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterGraficoComposicaoSalarial]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterGraficoComposicaoSalarial]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterGraficoComposicaoSalarial]
	@GuidUsuario AS UNIQUEIDENTIFIER = NULL,
    @Competencia CHAR(8) = NULL

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

--	Tabela temporária para armazenar os dados do Gráfico de Composição Salarial.
CREATE TABLE #TmpGraficoComposicaoSalarial (
	RANKING INT,
	TIPO VARCHAR(1),
	COR VARCHAR(7),
    GUIDUSUARIO UNIQUEIDENTIFIER,
    COMPETENCIA VARCHAR(8),
	MATRICULA VARCHAR(20),
	IDEVENTO INT,
	ORDEM_EVENTO TINYINT,
	DESCRICAO_EVENTO VARCHAR(75),
    VALOR DECIMAL(11, 2))

INSERT INTO #TmpGraficoComposicaoSalarial (RANKING, TIPO, COR, GUIDUSUARIO, COMPETENCIA, MATRICULA, IDEVENTO, ORDEM_EVENTO, DESCRICAO_EVENTO, VALOR)
     SELECT ROW_NUMBER() OVER (PARTITION BY MATRICULA, COMPETENCIA, CASE WHEN E.[TIPO] = 'V' THEN 1 ELSE 2 END ORDER BY ABS(CONVERT(DECIMAL(11, 2), CONVERT(VARCHAR(MAX), ISNULL(MDPE.[VALOR], 0)))) DESC) AS RANKING,
	        E.[TIPO],
	        NULL AS 'COR',
			U.[GUID],
			MDP.[COMPETENCIA],
			M.[MATRICULA],
			E.[ID],
			CASE WHEN E.[TIPO] = 'V' THEN 1 ELSE 2 END,
			E.[DESCRICAO],
			CONVERT(DECIMAL(11, 2), CONVERT(VARCHAR(MAX), ISNULL(MDPE.[VALOR], 0))) AS 'VALOR'
       FROM [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] MDP
 INNER JOIN [MATRICULAS] M
         ON MDP.[GUIDMATRICULA] = M.[GUID]
 INNER JOIN [MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] MDPE
         ON MDP.[GUID] = MDPE.GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO
 INNER JOIN [EVENTOS] E
         ON MDPE.[IDEVENTO] = E.[ID]
 INNER JOIN [USUARIOS] U
         ON M.[GUIDCOLABORADOR] = U.[GUIDCOLABORADOR]
      WHERE (@GuidUsuario IS NULL OR U.[GUID] = @GuidUsuario)
	    AND (@Competencia IS NULL OR MDP.[COMPETENCIA] = @Competencia)
   ORDER BY M.[MATRICULA],
            MDP.[COMPETENCIA] DESC,
			E.[ID]

UPDATE [#TmpGraficoComposicaoSalarial]
   SET COR = CASE WHEN ORDEM_EVENTO = 1 THEN
		 	      CASE ((RANKING - 1) % 3) + 1
				      WHEN 2 THEN '#198754'		--	SUCCESS
					  WHEN 3 THEN '#0dcaf0'		--	INFO
					  ELSE '#0d6efd' END		--	PRIMARY
                  WHEN ORDEM_EVENTO = 2 THEN
				  CASE ((RANKING - 1) % 3) + 1
					  WHEN 2 THEN '#dc3545'		--	DANGER
					  WHEN 3 THEN '#6c757d'		--	SECONDARY
					  ELSE '#ffc107' END		--	WARNING
			 END;

  SELECT GUIDUSUARIO,
		 COMPETENCIA,
		 VALOR,
		 MATRICULA,
		 DESCRICAO_EVENTO,
		 TIPO,
         COR
    FROM [#TmpGraficoComposicaoSalarial]
ORDER BY [MATRICULA],
         [COMPETENCIA] DESC,
		 [ORDEM_EVENTO],
		 [VALOR] DESC

DROP TABLE [#TmpGraficoComposicaoSalarial]

GO