--EXEC [UspObterCalculos]

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterCalculos]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterCalculos]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterCalculos]

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

 SELECT C.[ID],
        C.[DATA_INCLUSAO],
        C.[DATA_ULTIMA_ALTERACAO],
        C.[DESCRICAO],
	    C.[OBSERVACOES]
   FROM [dbo].[CALCULOS] AS C WITH(NOLOCK)

GO