--EXEC [UspObterMatriculasDemonstrativosPagamento]

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspObterMatriculaDemonstrativoPagamentoPorCompetenciaEMatricula]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspObterMatriculaDemonstrativoPagamentoPorCompetenciaEMatricula]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspObterMatriculaDemonstrativoPagamentoPorCompetenciaEMatricula]
	@Competencia AS CHAR(8),
	@Matricula AS VARCHAR(20)

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

          SELECT MDP.[GUID], MDP.[GUIDMATRICULA], MDP.[COMPETENCIA], MDP.[DATA_INCLUSAO], MDP.[DATA_ULTIMA_ALTERACAO],
                 MDP.[DATA_CONFIRMACAO],MDP.[IP_CONFIRMACAO],MDP.[CONTEUDO_ARQUIVO],
                 M.[GUID], M.[MATRICULA], M.[DATA_ADMISSAO], M.[DATA_DEMISSAO], M.[DATA_INCLUSAO], M.[DATA_ULTIMA_ALTERACAO],
		         M.[DESCRICAO_CARGO], M.[DESCRICAO_SETOR], M.[FAIXA_IR], M.[FAIXA_SF], M.[GUIDCOLABORADOR], M.[GUIDEMPREGADOR],
		         M.[FORMA_PAGAMENTO], M.[BANCO], M.[AGENCIA], M.[CONTA], M.[DV_CONTA], M.[CARGA_HORARIA], M.[SALARIO_NOMINAL],
                 PF.[GUIDPESSOA], PF.[CPF], PF.[RG], PF.[DATA_NASCIMENTO], PF.[NOME], PF.[NUMERO_CTPS], PF.[SERIE_CTPS], PF.[UF_CTPS],
                 PJ.[GUIDPESSOA], PJ.[CNPJ], PJ.[DATA_FUNDACAO], PJ.[RAZAO_SOCIAL], PJ.[IDUNIDADE_NEGOCIO],
		         MDPE.[GUID], MDPE.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO], MDPE.[IDEVENTO], MDPE.[REFERENCIA], MDPE.[VALOR],
		         E.[ID], E.[DATA_INCLUSAO], E.[DATA_ULTIMA_ALTERACAO], E.[DESCRICAO], E.[TIPO],
		         MDPT.[GUID], MDPT.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO], MDPT.[IDTOTALIZADOR], MDPT.[VALOR],
		         T.[ID], T.[DATA_INCLUSAO], T.[DATA_ULTIMA_ALTERACAO], T.[DESCRICAO]
            FROM [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO] AS MDP WITH(NOLOCK)
      INNER JOIN [dbo].[MATRICULAS] as M WITH(NOLOCK)
              ON MDP.[GUIDMATRICULA] = M.[GUID] 
      INNER JOIN [dbo].[PESSOAS_FISICAS] AS PF WITH(NOLOCK)
              ON M.[GUIDCOLABORADOR] = PF.[GUID]
      INNER JOIN [dbo].[PESSOAS_JURIDICAS] AS PJ WITH(NOLOCK)
              ON M.[GUIDEMPREGADOR] = PJ.[GUID]
 LEFT OUTER JOIN [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_EVENTOS] AS MDPE WITH(NOLOCK)
              ON MDP.[GUID] = MDPE.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
 LEFT OUTER JOIN [dbo].[EVENTOS] AS E WITH(NOLOCK)
              ON MDPE.[IDEVENTO] = E.[ID]
 LEFT OUTER JOIN [dbo].[MATRICULAS_DEMONSTRATIVOS_PAGAMENTO_TOTALIZADORES] AS MDPT WITH(NOLOCK)
              ON MDP.[GUID] = MDPT.[GUIDMATRICULA_DEMONSTRATIVO_PAGAMENTO]
 LEFT OUTER JOIN [dbo].[TOTALIZADORES] AS T WITH(NOLOCK)
              ON MDPT.[IDTOTALIZADOR] = T.[ID]
		   WHERE MDP.[COMPETENCIA] = @Competencia
		     AND M.[MATRICULA] = @Matricula

GO