If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspExcluirCompeticaoPorId]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspExcluirCompeticaoPorId]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspExcluirCompeticaoPorId]
	@Id AS UNIQUEIDENTIFIER

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

 DELETE C
   FROM [dbo].[Competicao] AS C
  WHERE C.[Id] = @Id

GO