INSERT [dbo].[BANDEIRAS_COMERCIAIS] ([ID], [DATA_INCLUSAO], [DATA_ULTIMA_ALTERACAO], [DESCRICAO]) VALUES (1, GETUTCDATE(), NULL, N'MACROMIX')
INSERT [dbo].[BANDEIRAS_COMERCIAIS] ([ID], [DATA_INCLUSAO], [DATA_ULTIMA_ALTERACAO], [DESCRICAO]) VALUES (2, GETUTCDATE(), NULL, N'RISSUL')
