--EXEC [UspObterEventoPorId] 1

If Exists(Select * From sysobjects Where ID = OBJECT_ID(N'[dbo].[UspExcluirMatriculaEspelhoPontoVinculosPorCompetenciaEIdMatricula]') And OBJECTPROPERTY(ID, N'IsProcedure') = 1)
	DROP PROCEDURE [dbo].[UspExcluirMatriculaEspelhoPontoVinculosPorCompetenciaEIdMatricula]
GO

SET QUOTED_IDENTIFIER OFF
SET ANSI_NULLS ON

GO

CREATE PROCEDURE [dbo].[UspExcluirMatriculaEspelhoPontoVinculosPorCompetenciaEIdMatricula]
	@Competencia AS CHAR(8),
	@GuidMatricula AS UNIQUEIDENTIFIER

WITH ENCRYPTION
AS

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

     DELETE MEPC
       FROM [dbo].[MATRICULAS_ESPELHOS_PONTO_CALCULOS] MEPC
 INNER JOIN [dbo].[MATRICULAS_ESPELHOS_PONTO] MEP
         ON MEPC.[GUIDMATRICULA_ESPELHO_PONTO] = MEP.[GUID]
	  WHERE MEP.[COMPETENCIA] = @Competencia
	    AND MEP.[GUIDMATRICULA] = @GuidMatricula

     DELETE MEPM
       FROM [dbo].[MATRICULAS_ESPELHOS_PONTO_MARCACOES] MEPM
 INNER JOIN [dbo].[MATRICULAS_ESPELHOS_PONTO] MEP
         ON MEPM.[GUIDMATRICULA_ESPELHO_PONTO] = MEP.[GUID]
	  WHERE MEP.[COMPETENCIA] = @Competencia
	    AND MEP.[GUIDMATRICULA] = @GuidMatricula

GO