ALTER TABLE [dbo].[UNIDADES_NEGOCIO] DROP CONSTRAINT [DF_UNIDADES_NEGOCIO_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[UNIDADES_NEGOCIO]    Script Date: 24/03/2024 22:15:28 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UNIDADES_NEGOCIO]') AND type in (N'U'))
	DROP TABLE [dbo].[UNIDADES_NEGOCIO]
GO

/****** Object:  Table [dbo].[UNIDADES_NEGOCIO]    Script Date: 24/03/2024 22:15:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UNIDADES_NEGOCIO](
	[ID] [int] NOT NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NOT NULL,
	[DESCRICAO] [varchar](75) NOT NULL,
 CONSTRAINT [PK_UNIDADES_NEGOCIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[UNIDADES_NEGOCIO] ADD  CONSTRAINT [DF_UNIDADES_NEGOCIO_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO