ALTER TABLE [dbo].[PESSOAS] DROP CONSTRAINT [DF_PESSOAS_DATA_INCLUSAO]
GO

/****** Object:  Table [dbo].[PESSOAS]    Script Date: 22/12/2024 01:58:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PESSOAS]') AND type in (N'U'))
	DROP TABLE [dbo].[PESSOAS]
GO

/****** Object:  Table [dbo].[PESSOAS]    Script Date: 22/12/2024 01:58:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOAS](
	[GUID] [uniqueidentifier] NOT NULL,
	[CEP] [char](8) NULL,
	[COMPLEMENTO] [varchar](30) NULL,
	[DATA_INCLUSAO] [datetime2](7) NOT NULL,
	[DATA_ULTIMA_ALTERACAO] [datetime2](7) NOT NULL,
	[EMAIL] [varchar](75) NULL,
	[NUMERO] [varchar](10) NULL,
	[TELEFONE] [varchar](30) NULL,
	[CHAVE_EXPORTACAO_IMPORTACAO] VARCHAR (16) NOT NULL,
 CONSTRAINT [PK_PESSOAS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PESSOAS] ADD  CONSTRAINT [DF_PESSOAS_DATA_INCLUSAO]  DEFAULT (getutcdate()) FOR [DATA_INCLUSAO]
GO