ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] DROP CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 22/12/2024 02:23:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PESSOAS_JURIDICAS]') AND type in (N'U'))
	DROP TABLE [dbo].[PESSOAS_JURIDICAS]
GO

/****** Object:  Table [dbo].[PESSOAS_JURIDICAS]    Script Date: 22/12/2024 02:23:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PESSOAS_JURIDICAS](
	[GUID] [uniqueidentifier] NOT NULL,
	[GUIDPESSOA] [uniqueidentifier] NOT NULL,
	[CNPJ] [char](14) NOT NULL,
	[DATA_FUNDACAO] [date] NULL,
	[LOGOTIPO] [varbinary](max) NULL,
	[RAZAO_SOCIAL] [varchar](100) NOT NULL,
	[IDUNIDADE_NEGOCIO] [int] NOT NULL,
 CONSTRAINT [PK_PESSOAS_JURIDICAS] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS] FOREIGN KEY([GUIDPESSOA])
REFERENCES [dbo].[PESSOAS] ([GUID])
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] CHECK CONSTRAINT [FK_PESSOAS_JURIDICAS_PESSOAS]
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS]  WITH CHECK ADD  CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO] FOREIGN KEY([IDUNIDADE_NEGOCIO])
REFERENCES [dbo].[UNIDADES_NEGOCIO] ([ID])
GO

ALTER TABLE [dbo].[PESSOAS_JURIDICAS] CHECK CONSTRAINT [FK_PESSOAS_JURIDICAS_UNIDADES_NEGOCIO]
GO